In [1]:
import numpy as np

In [4]:
a = np.zeros([4, 3])
b = np.ones([4, 3])

In [5]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## stack

In [17]:
np.vstack((a, b)).shape

(8, 3)

In [15]:
np.hstack((a, b)).shape

(4, 6)

In [12]:
test_1 = np.stack((a, b), axis = 0)

print(test_1)
print(test_1.shape)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
(2, 4, 3)


In [13]:
test_2 = np.stack((a, b), axis = 1)

print(test_2)
print(test_2.shape)

[[[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]]
(4, 2, 3)


In [14]:
test_3 = np.stack((a, b), axis = 2)

print(test_3)
print(test_3.shape)

[[[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]]
(4, 3, 2)


## split

In [25]:
a = np.arange(0, 16).reshape([4, 4])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [28]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [37]:
np.split(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [41]:
c = np.arange(12).reshape(3, 4)
x = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
y = np.zeros((3, 4))

In [42]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
c.shape

(3, 4)

In [43]:
x

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [44]:
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
# 좌표를 반환해 줌!

np.where((c>5))

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [49]:
coords = np.where((a>3) & (a<8))
coords

(array([1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [51]:
d = c.copy()
d[coords] = 77
d

array([[ 0,  1,  2,  3],
       [77, 77, 77, 77],
       [ 8,  9, 10, 11]])